"""In-memory investment memo PDF generation via ReportLab."""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer

from shared.models import verdict_from_deal_score

_PLACEHOLDER_FINANCIAL_PATTERNS = (
    "$50",
    "$95B",
    "illustrative",
    "provisional valuation band",
    "large-cap comparables",
    "in this demo",
)


def normalize_deal_score_fields(memo: dict[str, Any]) -> dict[str, Any]:
    """Clamp deal_score to 0–100, align deal_verdict to score bands, coerce risks_flagged_count."""
    out = dict(memo)
    try:
        s = int(out.get("deal_score", 50))
    except (TypeError, ValueError):
        s = 50
    out["deal_score"] = max(0, min(100, s))
    out["deal_verdict"] = verdict_from_deal_score(out["deal_score"])
    try:
        out["risks_flagged_count"] = max(0, int(out.get("risks_flagged_count", 0)))
    except (TypeError, ValueError):
        out["risks_flagged_count"] = 0
    return out


def _sanitize_financial_highlights(memo_data: dict[str, Any]) -> None:
    financial_highlights = memo_data.get("financial_highlights", "")
    if not isinstance(financial_highlights, str):
        return
    if any(p.lower() in financial_highlights.lower() for p in _PLACEHOLDER_FINANCIAL_PATTERNS):
        memo_data["financial_highlights"] = (
            "No financial documents were provided. Valuation cannot be modelled "
            "from public data alone. Recommend requesting audited financials before proceeding."
        )


def build_memo_pdf_bytes(memo_data: dict[str, Any]) -> bytes:
    """Build a PDF investment memo in memory and return raw bytes."""
    memo_data = normalize_deal_score_fields(dict(memo_data))
    _sanitize_financial_highlights(memo_data)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=inch,
        leftMargin=inch,
        topMargin=inch,
        bottomMargin=inch,
    )

    styles = getSampleStyleSheet()
    accent = HexColor("#1a365d")

    title_style = ParagraphStyle(
        "Title", parent=styles["Heading1"], fontSize=20, textColor=accent, spaceAfter=6
    )
    h2_style = ParagraphStyle(
        "H2", parent=styles["Heading2"], fontSize=13, textColor=accent, spaceAfter=4
    )
    body_style = styles["BodyText"]
    body_style.spaceAfter = 6

    recommendation = str(memo_data.get("recommendation", "")).upper()
    confidence = str(memo_data.get("confidence", "")).upper()
    rec_color = {"INVEST": "#276749", "CONDITIONAL": "#975a16", "PASS": "#9b2c2c"}.get(
        recommendation, "#2d3748"
    )

    verdict_style = ParagraphStyle(
        "Verdict", parent=styles["Heading1"], fontSize=16, textColor=HexColor(rec_color)
    )

    company = memo_data.get("company_name", "Unknown")
    content: list[Any] = []
    content.append(Paragraph(f"Investment Memo: {company}", title_style))
    content.append(
        Paragraph(
            f"Generated by DealFlow AI — {datetime.now().strftime('%B %d, %Y')}",
            body_style,
        )
    )
    content.append(HRFlowable(width="100%", thickness=2, color=accent))
    content.append(Spacer(1, 12))

    content.append(
        Paragraph(f"Recommendation: {recommendation} ({confidence} confidence)", verdict_style)
    )
    ds = memo_data.get("deal_score", 50)
    dv = memo_data.get("deal_verdict", verdict_from_deal_score(ds))
    rc = memo_data.get("risks_flagged_count", 0)
    content.append(
        Paragraph(
            f"Deal score: {ds}/100 — {dv} — {rc} risk(s) flagged (Judge)",
            body_style,
        )
    )
    content.append(Spacer(1, 12))

    sections = [
        ("Executive Summary", "executive_summary"),
        ("Financial Highlights", "financial_highlights"),
        ("Legal Risk Assessment", "legal_risks"),
        ("Market Position", "market_position"),
        ("Suggested Deal Terms", "deal_terms_suggested"),
    ]

    for title, key in sections:
        content.append(Paragraph(title, h2_style))
        content.append(Paragraph(str(memo_data.get(key, "N/A")), body_style))
        content.append(Spacer(1, 8))

    red_flags = memo_data.get("red_flags", [])
    if red_flags:
        content.append(Paragraph("Red Flags", h2_style))
        for flag in red_flags:
            content.append(Paragraph(f"• {flag}", body_style))
        content.append(Spacer(1, 8))

    content.append(HRFlowable(width="100%", thickness=1, color=HexColor("#e2e8f0")))
    content.append(
        Paragraph("Confidential — Generated by DealFlow AI multi-agent system", body_style)
    )

    doc.build(content)
    return buffer.getvalue()
