"""
Synthesis Agent — DealFlow AI
Framework: LangGraph
Model: Claude Sonnet via AI/ML API

The final agent. Waits for all specialist signals, synthesizes findings,
writes the investment memo, and generates a PDF report.
"""

import asyncio
import json
import logging
import os
from datetime import datetime
from pathlib import Path

from dotenv import load_dotenv
from langchain_core.tools import tool
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import InMemorySaver
from thenvoi import Agent
from thenvoi.adapters import LangGraphAdapter
from thenvoi.config import load_agent_config

from shared.models import FinancialAnalysis, LegalRiskAnalysis, MarketResearch, InvestmentMemo
from shared.prompts import SYNTHESIS_PROMPT

load_dotenv()
logger = logging.getLogger(__name__)

# -------------------------------------------------------------------
# Model — Claude Sonnet via AI/ML API (best reasoning for synthesis)
# -------------------------------------------------------------------
llm = ChatOpenAI(
    model="claude-sonnet-4-5",
    base_url="https://api.aimlapi.com/v1",
    api_key=os.environ["AIML_API_KEY"],
    temperature=0.3,
)

# -------------------------------------------------------------------
# Synthesis and PDF generation tools
# -------------------------------------------------------------------

@tool
def parse_signal_payload(message: str) -> dict:
    """
    Extract the JSON payload from a SIGNAL: message posted by a specialist agent.
    Returns {signal_type, payload} or {error}.
    """
    try:
        lines = message.strip().split("\n", 1)
        if lines[0].startswith("SIGNAL:"):
            signal_type = lines[0].replace("SIGNAL:", "").strip()
            payload = json.loads(lines[1]) if len(lines) > 1 else {}
            return {"signal_type": signal_type, "payload": payload}
    except Exception as e:
        return {"error": str(e)}
    return {"error": "Not a valid SIGNAL message"}


@tool
def generate_pdf_memo(memo_data: dict) -> str:
    """
    Generate a formatted PDF investment memo from the InvestmentMemo data.
    Returns the file path of the saved PDF.
    """
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import inch
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
        from reportlab.lib.colors import HexColor

        output_dir = Path(os.environ.get("UPLOAD_DIR", "./uploads"))
        output_dir.mkdir(exist_ok=True)

        company = memo_data.get("company_name", "Unknown")
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        pdf_path = output_dir / f"investment_memo_{company.replace(' ', '_')}_{timestamp}.pdf"

        doc = SimpleDocTemplate(str(pdf_path), pagesize=letter,
                                rightMargin=inch, leftMargin=inch,
                                topMargin=inch, bottomMargin=inch)

        styles = getSampleStyleSheet()
        accent = HexColor("#1a365d")

        title_style = ParagraphStyle("Title", parent=styles["Heading1"],
                                     fontSize=20, textColor=accent, spaceAfter=6)
        h2_style = ParagraphStyle("H2", parent=styles["Heading2"],
                                  fontSize=13, textColor=accent, spaceAfter=4)
        body_style = styles["BodyText"]
        body_style.spaceAfter = 6

        recommendation = memo_data.get("recommendation", "").upper()
        confidence = memo_data.get("confidence", "").upper()
        rec_color = {"INVEST": "#276749", "CONDITIONAL": "#975a16", "PASS": "#9b2c2c"}.get(recommendation, "#2d3748")

        verdict_style = ParagraphStyle("Verdict", parent=styles["Heading1"],
                                       fontSize=16, textColor=HexColor(rec_color))

        content = []
        content.append(Paragraph(f"Investment Memo: {company}", title_style))
        content.append(Paragraph(f"Generated by DealFlow AI — {datetime.now().strftime('%B %d, %Y')}", body_style))
        content.append(HRFlowable(width="100%", thickness=2, color=accent))
        content.append(Spacer(1, 12))

        content.append(Paragraph(f"Recommendation: {recommendation} ({confidence} confidence)", verdict_style))
        content.append(Spacer(1, 12))

        sections = [
            ("Executive Summary", "executive_summary"),
            ("Financial Highlights", "financial_highlights"),
            ("Legal Risk Assessment", "legal_risks"),
            ("Market Position", "market_position"),
            ("Suggested Deal Terms", "deal_terms_suggested"),
        ]

        for title, key in sections:
            content.append(Paragraph(title, h2_style))
            content.append(Paragraph(memo_data.get(key, "N/A"), body_style))
            content.append(Spacer(1, 8))

        red_flags = memo_data.get("red_flags", [])
        if red_flags:
            content.append(Paragraph("Red Flags", h2_style))
            for flag in red_flags:
                content.append(Paragraph(f"• {flag}", body_style))
            content.append(Spacer(1, 8))

        content.append(HRFlowable(width="100%", thickness=1, color=HexColor("#e2e8f0")))
        content.append(Paragraph("Confidential — Generated by DealFlow AI multi-agent system", body_style))

        doc.build(content)
        logger.info(f"PDF memo saved to {pdf_path}")
        return str(pdf_path)

    except Exception as e:
        logger.error(f"PDF generation failed: {e}")
        return f"ERROR: {e}"


@tool
def format_final_signal(memo: dict) -> str:
    """Format InvestmentMemo as a SIGNAL message for the Band room."""
    return f"SIGNAL:investment_memo\n{json.dumps(memo, indent=2)}"


# -------------------------------------------------------------------
# Agent setup
# -------------------------------------------------------------------

def create_synthesis() -> Agent:
    agent_id, api_key = load_agent_config("synthesis")

    adapter = LangGraphAdapter(
        llm=llm,
        checkpointer=InMemorySaver(),
        additional_tools=[
            parse_signal_payload,
            generate_pdf_memo,
            format_final_signal,
        ],
        system_prompt=SYNTHESIS_PROMPT,
    )

    return Agent.create(
        adapter=adapter,
        agent_id=agent_id,
        api_key=api_key,
    )


async def run_synthesis():
    logger.info("Synthesis Agent starting (Claude Sonnet via AI/ML API)...")
    agent = create_synthesis()
    await agent.run()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(run_synthesis())
